# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlist',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('notified', 'Notified'), ('converted', 'Converted'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
