# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_amount_ticket_payment_status_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(
                condition=models.Q(('stripe_session_id__isnull', False)),
                fields=('stripe_session_id',),
                name='unique_paid_stripe_payment_reference'
            ),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('payment_status', 'paid'),
                    ('status', 'active')
                ),
                fields=('user', 'event'),
                name='unique_active_paid_ticket_per_user_event'
            ),
        ),
    ]
